"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { buttonClasses, INPUT_CLASSES, noticeClasses } from "@/components/ui";
import type { EventConfiguration } from "@/lib/events/configuration";

type Props = { eventSlug: string; configuration: EventConfiguration };
type Message = { kind: "positive" | "negative"; text: string } | null;
function timeValue(minutes: number) { return `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`; }
function minutes(value: FormDataEntryValue | null) { const match = /^(\d{2}):(\d{2})$/.exec(String(value ?? "")); return match ? Number(match[1]) * 60 + Number(match[2]) : Number.NaN; }

export function SettingsEditor({ eventSlug, configuration }: Props) {
	const router = useRouter(); const [message, setMessage] = useState<Message>(null); const [pending, setPending] = useState(false);
	async function request(path: string, method: string, body: unknown) { setPending(true); setMessage(null); try { const response = await fetch(`/api/admin/events/${eventSlug}/settings${path}`, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !data.ok) { setMessage({ kind: "negative", text: data.error ?? "Could not save changes." }); return false; } setMessage({ kind: "positive", text: "Saved." }); router.refresh(); return true; } catch { setMessage({ kind: "negative", text: "Network error. Your changes were not saved." }); return false; } finally { setPending(false); } }
	function move(kind: "rooms" | "tracks" | "tasks", ids: string[], index: number, delta: number) { const next = index + delta; if (next < 0 || next >= ids.length) return; const ordered = [...ids]; [ordered[index], ordered[next]] = [ordered[next]!, ordered[index]!]; void request(`/${kind}`, "PATCH", { action: "reorder", orderedIds: ordered }); }
	const event = configuration.event;
	return <div className="mt-8 space-y-10"><section className="rounded-lg border border-neutral-800 bg-neutral-900 p-5"><h2 className="text-lg font-semibold text-neutral-100">Event details</h2><p className="mt-1 text-sm text-neutral-400">The slug is permanent. Changes that would put an existing session outside these dates or hours are rejected.</p><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void request("", "PATCH", { name: f.get("name"), startDay: f.get("startDay"), endDay: f.get("endDay"), timezone: f.get("timezone"), dayStartMinutes: minutes(f.get("dayStart")), dayEndMinutes: minutes(f.get("dayEnd")), slotDurationMinutes: Number(f.get("slotDuration")), trackConflictPolicy: f.get("trackConflictPolicy") }); }}><Field label="Event name" name="name" defaultValue={event.name} /><Field label="Timezone" name="timezone" defaultValue={event.timezone} /><Field label="Start date" name="startDay" type="date" defaultValue={event.start_day ?? ""} /><Field label="End date" name="endDay" type="date" defaultValue={event.end_day ?? ""} /><Field label="Day starts" name="dayStart" type="time" defaultValue={timeValue(event.day_start_minutes)} /><Field label="Day ends" name="dayEnd" type="time" defaultValue={timeValue(event.day_end_minutes)} /><label className="block space-y-1.5 text-sm"><span className="font-medium text-neutral-200">Slot duration</span><select name="slotDuration" defaultValue={String(event.slot_duration_minutes)} className={`w-full ${INPUT_CLASSES}`}><option value="15">15 minutes</option><option value="20">20 minutes</option><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option><option value="120">120 minutes</option></select></label><label className="block space-y-1.5 text-sm"><span className="font-medium text-neutral-200">Track conflict policy</span><select name="trackConflictPolicy" defaultValue={event.track_conflict_policy} className={`w-full ${INPUT_CLASSES}`}><option value="hard">Hard: block overlapping sessions in the same track</option><option value="allow">Allow: permit overlapping sessions in the same track</option></select></label><div className="sm:col-span-2"><button disabled={pending} className={buttonClasses("primary")}>Save event details</button></div></form></section>
		<Collection id="rooms" title="Rooms" description="Rooms appear as schedule columns." pending={pending} onCreate={(data) => request("/rooms", "POST", data)}><form className="flex flex-wrap gap-2" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void request("/rooms", "POST", { name: f.get("name") }); e.currentTarget.reset(); }}><Field label="New room name" name="name" /><button disabled={pending} className={buttonClasses("secondary")}>Add room</button></form><Rows rows={configuration.rooms} pending={pending} onMove={(index, delta) => move("rooms", configuration.rooms.map((item) => item.id), index, delta)} onSave={(id, data) => request("/rooms", "PATCH", { id, ...data })} onDelete={(id) => request("/rooms", "DELETE", { id })} render={(row) => <Field label="Room name" name="name" defaultValue={row.name} />} /></Collection>
		<Collection id="tracks" title="Agenda tracks" description="Tracks group sessions within your agenda." pending={pending} onCreate={(data) => request("/tracks", "POST", data)}><form className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void request("/tracks", "POST", { name: f.get("name"), slug: f.get("slug") }); e.currentTarget.reset(); }}><Field label="Track name" name="name" /><Field label="Track slug" name="slug" placeholder="workshops" pattern="(?:[a-z0-9]|-)+" /><button disabled={pending} className={`self-end ${buttonClasses("secondary")}`}>Add track</button></form><Rows rows={configuration.tracks} pending={pending} onMove={(index, delta) => move("tracks", configuration.tracks.map((item) => item.id), index, delta)} onSave={(id, data) => request("/tracks", "PATCH", { id, ...data })} onDelete={(id) => request("/tracks", "DELETE", { id })} render={(row) => <><Field label="Track name" name="name" defaultValue={row.name} /><Field label="Track slug" name="slug" defaultValue={row.slug} pattern="(?:[a-z0-9]|-)+" /></>} /></Collection>
		<Collection id="tasks" title="Speaker task templates" description="Accepted speakers receive one task for each active template." pending={pending} onCreate={(data) => request("/tasks", "POST", data)}><form className="grid gap-2 sm:grid-cols-4" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void request("/tasks", "POST", { key: f.get("key"), label: f.get("label"), kind: f.get("kind"), required: f.get("required") === "on" }); e.currentTarget.reset(); }}><Field label="Task key" name="key" placeholder="slides" pattern="(?:[a-z0-9]|-)+" /><Field label="Task label" name="label" /><label className="block space-y-1.5 text-sm"><span className="font-medium text-neutral-200">Kind</span><select name="kind" defaultValue="file" className={`w-full ${INPUT_CLASSES}`}><option value="file">File</option><option value="text">Text</option></select></label><label className="flex items-end gap-2 pb-2 text-sm text-neutral-200"><input name="required" type="checkbox" defaultChecked /> Required</label><button disabled={pending} className={`sm:col-span-4 justify-self-start ${buttonClasses("secondary")}`}>Add task</button></form><Rows rows={configuration.tasks} pending={pending} onMove={(index, delta) => move("tasks", configuration.tasks.map((item) => item.id), index, delta)} onSave={(id, data) => request("/tasks", "PATCH", { id, ...data, required: data.required === "on" })} onDelete={(id) => request("/tasks", "DELETE", { id })} render={(row) => <><Field label={`Task label (${row.key})`} name="label" defaultValue={row.label} /><label className="block space-y-1.5 text-sm"><span className="font-medium text-neutral-200">Kind</span><select name="kind" defaultValue={row.task_kind} className={`w-full ${INPUT_CLASSES}`}><option value="file">File</option><option value="text">Text</option></select></label><label className="flex items-end gap-2 pb-2 text-sm text-neutral-200"><input name="required" type="checkbox" defaultChecked={row.required === 1} /> Required</label></>} /></Collection>
		{message ? <p aria-live="polite" className={noticeClasses(message.kind)}>{message.text}</p> : null}</div>;
}
function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="block space-y-1.5 text-sm"><span className="font-medium text-neutral-200">{label}</span><input required {...props} className={`w-full ${INPUT_CLASSES}`} /></label>; }
function Collection({ id, title, description, children }: { id: string; title: string; description: string; pending: boolean; onCreate: (data: Record<string, unknown>) => Promise<boolean>; children: React.ReactNode }) { return <section id={id} className="scroll-mt-6 rounded-lg border border-neutral-800 bg-neutral-900 p-5"><h2 className="text-lg font-semibold text-neutral-100">{title}</h2><p className="mt-1 text-sm text-neutral-400">{description}</p><div className="mt-5 space-y-4">{children}</div></section>; }
function Rows<T extends { id: string }>({ rows, pending, onMove, onSave, onDelete, render }: { rows: T[]; pending: boolean; onMove: (index: number, delta: number) => void; onSave: (id: string, data: Record<string, string>) => Promise<boolean>; onDelete: (id: string) => Promise<boolean>; render: (row: T) => React.ReactNode }) { return <ul className="space-y-3">{rows.map((row, index) => <li key={row.id} className="rounded-md border border-neutral-800 p-3"><form className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]" onSubmit={(e) => { e.preventDefault(); const values = Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string, string>; void onSave(row.id, values); }}>{render(row)}<div className="flex items-end gap-2"><button type="submit" disabled={pending} className={buttonClasses("secondary")}>Save</button><button type="button" disabled={pending || index === 0} onClick={() => onMove(index, -1)} className={buttonClasses("secondary", "sm")}>Up</button><button type="button" disabled={pending || index === rows.length - 1} onClick={() => onMove(index, 1)} className={buttonClasses("secondary", "sm")}>Down</button><button type="button" disabled={pending || rows.length === 1} onClick={() => { if (window.confirm("Retire this item? Historical data stays intact.")) void onDelete(row.id); }} className="rounded-md px-3 py-2 text-sm font-medium text-red-300 hover:bg-red-950/50 disabled:opacity-50">Retire</button></div></form></li>)}</ul>; }
