import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import type { CSSProperties } from "react";
import { getDb } from "@/lib/db/cloudflare";
import { buildPublicEmbedPayload } from "@/lib/embeds/embed";

type Props = { params: Promise<{ eventSlug: string; embedSlug: string }> };
export default async function PublicEmbedPage({ params }: Props) { const { eventSlug, embedSlug } = await params; const payload = await buildPublicEmbedPayload(await getDb(), eventSlug, embedSlug); if (!payload) notFound(); const fields = new Set(payload.embed.config.visibleFields); const style = { "--embed-accent": payload.embed.config.brandColor } as CSSProperties;
	return <main style={style} className="mx-auto min-h-dvh max-w-5xl bg-neutral-950 px-4 py-6 text-neutral-200"><header className="border-b border-neutral-800 pb-4"><p className="text-xs uppercase tracking-wide text-neutral-500">{payload.embed.name}</p><h1 className="mt-1 text-2xl font-semibold text-neutral-100">{payload.event.name}</h1></header>{payload.embed.widgetType === "speakers" || payload.embed.widgetType === "speaker_gallery" ? <SpeakerWidget payload={payload} gallery={payload.embed.widgetType === "speaker_gallery"} fields={fields} /> : payload.embed.widgetType === "itinerary" ? <ItineraryWidget payload={payload} /> : <SessionWidget payload={payload} agenda={payload.embed.widgetType === "agenda"} fields={fields} />}</main>;
}
type Payload = NonNullable<Awaited<ReturnType<typeof buildPublicEmbedPayload>>>;
function SessionWidget({ payload, agenda, fields }: { payload: Payload; agenda: boolean; fields: Set<string> }) { return <ul className={agenda ? "mt-6 divide-y divide-neutral-800" : "mt-6 grid gap-4 sm:grid-cols-2"}>{payload.sessions.map((session) => <li key={session.id} className={agenda ? "py-4" : "rounded-lg border border-neutral-800 p-4"}><div className="h-1 w-12 rounded bg-[var(--embed-accent)]" />{fields.has("time") ? <p className="mt-3 font-mono text-xs text-neutral-500">{new Intl.DateTimeFormat("en", { timeZone: payload.event.timezone, dateStyle: "medium", timeStyle: "short" }).format(session.startsAt)}</p> : null}{fields.has("title") ? <Link target="_blank" href={session.url} className="mt-1 block font-semibold text-neutral-100 hover:underline">{session.title}</Link> : null}<p className="mt-1 text-sm text-neutral-400">{fields.has("room") ? session.room : null}{fields.has("room") && fields.has("track") ? " · " : null}{fields.has("track") ? session.track : null}{fields.has("format") ? ` · ${session.format}` : null}</p>{fields.has("speakers") && session.speakers.length ? <p className="mt-2 text-sm text-neutral-300">{session.speakers.join(", ")}</p> : null}{fields.has("abstract") && session.abstract ? <p className="mt-2 text-sm leading-6 text-neutral-400">{session.abstract}</p> : null}</li>)}</ul>; }
function SpeakerWidget({ payload, gallery, fields }: { payload: Payload; gallery: boolean; fields: Set<string> }) { return <ul className={gallery ? "mt-6 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4" : "mt-6 divide-y divide-neutral-800"}>{payload.speakers.map((speaker) => <li key={speaker.id} className={gallery ? "rounded-lg border border-neutral-800 p-4 text-center" : "py-4"}>{fields.has("headshot") && speaker.headshotUrl ? <Image src={speaker.headshotUrl} width={80} height={80} alt="" className="mx-auto mb-3 h-20 w-20 rounded-full object-cover" unoptimized /> : null}<Link target="_blank" href={speaker.url} className="font-semibold text-neutral-100 hover:underline">{speaker.name}</Link>{fields.has("jobTitle") || fields.has("company") ? <p className="mt-1 text-sm text-neutral-500">{[fields.has("jobTitle") ? speaker.jobTitle : null, fields.has("company") ? speaker.company : null].filter(Boolean).join(" · ")}</p> : null}{fields.has("bio") && speaker.bio ? <p className="mt-2 text-sm leading-6 text-neutral-400">{speaker.bio}</p> : null}</li>)}</ul>; }
function ItineraryWidget({ payload }: { payload: Payload }) {
	const days = new Map<string, Payload["sessions"]>();
	for (const session of payload.sessions) { const day = new Intl.DateTimeFormat("en", { timeZone: payload.event.timezone, dateStyle: "full" }).format(session.startsAt); days.set(day, [...(days.get(day) ?? []), session]); }
	return <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="h-1 w-12 rounded bg-[var(--embed-accent)]" /><h2 className="mt-4 text-xl font-semibold">Build your itinerary</h2><p className="mt-2 text-sm text-neutral-400">Choose from {payload.sessions.length} published sessions.</p></div><Link target="_blank" href={payload.itineraryUrl} className="inline-block rounded px-4 py-2 text-sm font-medium text-white" style={{ backgroundColor: payload.embed.config.brandColor }}>Open full itinerary</Link></div><div className="mt-6 space-y-7">{[...days].map(([day, sessions]) => <section key={day}><h3 className="border-b border-neutral-800 pb-2 text-sm font-semibold text-neutral-300">{day}</h3><ul className="divide-y divide-neutral-800">{sessions.map((session) => <li key={session.id} className="grid gap-1 py-4 sm:grid-cols-[8rem_1fr_auto]"><time className="font-mono text-xs text-neutral-500">{new Intl.DateTimeFormat("en", { timeZone: payload.event.timezone, timeStyle: "short" }).format(session.startsAt)}</time><div><Link target="_blank" href={session.url} className="font-medium text-neutral-100 hover:underline">{session.title}</Link>{session.speakers.length ? <p className="mt-1 text-sm text-neutral-400">{session.speakers.join(", ")}</p> : null}</div><span className="text-xs text-neutral-500">{session.room}</span></li>)}</ul></section>)}</div></section>;
}
