import { NextResponse } from "next/server";
import { authorizeEventAdminApi } from "@/lib/auth/admin";
import { isJsonObject, readBoundedJson } from "@/lib/cfp/request";
import { getDb } from "@/lib/db/cloudflare";
import { createRoom, loadEventConfiguration, reorderConfigurationRows } from "@/lib/events/configuration";
import { requireWritableEventBySlug } from "@/lib/events/writability";
import { mutateEventRoomConfiguration } from "@/lib/realtime/event-room";
type Context = { params: Promise<{ eventSlug: string }> };
function failed(error: unknown) { return NextResponse.json({ ok: false, error: error instanceof Error ? error.message : "Room update failed" }, { status: error instanceof Error && "status" in error && typeof error.status === "number" ? error.status : 400 }); }
async function accessFor(context: Context) { const { eventSlug } = await context.params; const db = await getDb(); return { eventSlug, db, access: await authorizeEventAdminApi(db, eventSlug) }; }
type JsonBody = { ok: true; value: Record<string, unknown> } | { ok: false; status: number; error: string };
async function body(request: Request): Promise<JsonBody> { const parsed = await readBoundedJson(request, 16 * 1024); if (!parsed.ok) return { ok: false, status: parsed.status, error: parsed.error }; if (!isJsonObject(parsed.value)) return { ok: false, status: 400, error: "Expected JSON object" }; return { ok: true, value: parsed.value }; }
export async function GET(_request: Request, context: Context) { const { db, access } = await accessFor(context); if (!access) return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 }); return NextResponse.json({ ok: true, rooms: (await loadEventConfiguration(db, access.event.id)).rooms }); }
export async function POST(request: Request, context: Context) { const { eventSlug, db, access } = await accessFor(context); if (!access) return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 }); try { await requireWritableEventBySlug(db, eventSlug); } catch (error) { return failed(error); } const parsed = await body(request); if (!parsed.ok) return NextResponse.json({ ok: false, error: parsed.error }, { status: parsed.status }); try { await createRoom(db, access.event.id, parsed.value.name); return NextResponse.json({ ok: true }); } catch (error) { return failed(error); } }
export async function PATCH(request: Request, context: Context) { const { eventSlug, db, access } = await accessFor(context); if (!access) return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 }); try { await requireWritableEventBySlug(db, eventSlug); } catch (error) { return failed(error); } const parsed = await body(request); if (!parsed.ok) return NextResponse.json({ ok: false, error: parsed.error }, { status: parsed.status }); try { if (parsed.value.action === "reorder") { await reorderConfigurationRows(db, access.event.id, "rooms", parsed.value.orderedIds); return NextResponse.json({ ok: true }); } const result = await mutateEventRoomConfiguration(access.event.id, { action: "room-update", id: parsed.value.id, name: parsed.value.name }); return result.ok ? NextResponse.json({ ok: true }) : NextResponse.json(result, { status: result.status }); } catch (error) { return failed(error); } }
export async function DELETE(request: Request, context: Context) { const { eventSlug, db, access } = await accessFor(context); if (!access) return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 }); try { await requireWritableEventBySlug(db, eventSlug); } catch (error) { return failed(error); } const parsed = await body(request); if (!parsed.ok) return NextResponse.json({ ok: false, error: parsed.error }, { status: parsed.status }); try { const result = await mutateEventRoomConfiguration(access.event.id, { action: "room-delete", id: parsed.value.id }); return result.ok ? NextResponse.json({ ok: true }) : NextResponse.json(result, { status: result.status }); } catch (error) { return failed(error); } }
