import { AdminEventNav } from "@/components/admin-event-nav";
import { PageHeader } from "@/components/page-header";
import { assertCanManageEvent } from "@/lib/auth/admin";
import { getDb } from "@/lib/db/cloudflare";
import type { ContentRevisionRow, SubmissionRow } from "@/lib/db/types";
import { sessionContentFromRow } from "@/lib/content/revisions";
import { ContentConsole } from "./content-console";

function parseSnapshot(row: ContentRevisionRow): Record<string, unknown> { try { return JSON.parse(row.snapshot_json) as Record<string, unknown>; } catch { return {}; } }
export default async function ContentPage({ params }: { params: Promise<{ eventSlug: string }> }) { const { eventSlug } = await params; const db = await getDb(); const { event } = await assertCanManageEvent(db, eventSlug); const [submissions, revisions, speakerRows, speakerRevisions] = await Promise.all([db.prepare("SELECT s.*, CASE WHEN h.approved_revision_id IS NULL THEN 0 ELSE 1 END AS has_approved_snapshot FROM submissions s LEFT JOIN content_heads h ON h.event_id = s.event_id AND h.entity_type = 'session' AND h.entity_id = s.id WHERE s.event_id = ? AND s.status IN ('accepted','scheduled','published') ORDER BY s.updated_at DESC").bind(event.id).all<SubmissionRow & { has_approved_snapshot: number }>(), db.prepare("SELECT * FROM content_revisions WHERE event_id = ? AND entity_type = 'session' ORDER BY created_at DESC").bind(event.id).all<ContentRevisionRow>(), db.prepare(`SELECT DISTINCT p.id AS person_id, COALESCE(sp.display_name, p.name, p.email) AS name, p.email, COALESCE(sp.bio, '') AS bio, CASE WHEN sp.headshot_asset_id IS NULL THEN 0 ELSE 1 END AS has_headshot FROM people p INNER JOIN submission_speakers ss ON ss.person_id = p.id INNER JOIN submissions s ON s.id = ss.submission_id AND s.event_id = ? LEFT JOIN speaker_profiles sp ON sp.event_id = s.event_id AND sp.person_id = p.id WHERE s.status IN ('accepted','scheduled','published') AND ss.status IN ('pending','confirmed') ORDER BY name`).bind(event.id).all<{ person_id: string; name: string; email: string; bio: string; has_headshot: number }>(), db.prepare("SELECT * FROM content_revisions WHERE event_id = ? AND entity_type = 'speaker' ORDER BY created_at DESC").bind(event.id).all<ContentRevisionRow>()]); const shapeRevision = (row: ContentRevisionRow) => ({ id: row.id, number: row.revision_number, editorName: row.editor_name, createdAt: row.created_at, snapshot: parseSnapshot(row), restoredFrom: row.restored_from_revision_id }); const sessions = submissions.results.map((row) => ({ id: row.id, ...sessionContentFromRow(row), status: row.status, hasApprovedSnapshot: row.has_approved_snapshot === 1, revisions: revisions.results.filter((revision) => revision.entity_id === row.id).map(shapeRevision) })); const speakers = speakerRows.results.map((row) => ({ personId: row.person_id, name: row.name, email: row.email, bio: row.bio, hasHeadshot: row.has_headshot === 1, revisions: speakerRevisions.results.filter((revision) => revision.entity_id === row.person_id).map(shapeRevision) })); return <div className="min-h-dvh bg-neutral-950 text-neutral-200"><AdminEventNav eventSlug={event.slug} /><main className="mx-auto max-w-6xl px-4 py-10"><PageHeader eyebrow="Organizer · Content" title={event.name} description="Edit session and speaker copy, restore earlier versions, and approve what the public schedule shows." /><ContentConsole eventSlug={event.slug} sessions={sessions} speakers={speakers} /></main></div>; }
